### ISSUE TITLE
Confusion with developer docs when switching to Windows 10

### ISSUE THREAD

**Issue by CoolGames** [OSVR/OSVR-General#8]
I followed the [developer instructions](http://osvr.github.io/using/) as I had done on Ubuntu on same machine now running Windows 10.
I ended up with portrait single screen on **OSVR HDK V1.3 HMD**.
I tried better written [installation using the developer docs](https://osvrdevportal.atlassian.net/wiki/display/DD/Setting+up+the+Hacker+Development+Kit+1.3).

There are many **TBD** situations that I needed that have left me with an unusable **OSVR HMD display** after following instructions.

[FAQ and Troubleshooting](https://osvrdevportal.atlassian.net/wiki/display/DD/FAQ+and+Troubleshooting) does not offer any solution to the OSVR orientation issue.

Although on a positive note.
OSVR Control ran the Firmware Update as well as OSVR Server and Tracker Viewer on Windows 10.

**Comment by CoolGames** [comment]
HP Sprout has NVIDIA not connected to external wires.
The Internal display is an **INTEL HD** that has single device split to drive
1920x1024 Touch, 1024x768 Projector, 1920x1024 external HDMI so it is NOT using the
NVIDIA for direct drive of HDMI connector.
[HP Sprout User Manual](http://h10032.www1.hp.com/ctg/Manual/c04496534)  is needed with significant experimentation to succeed with mirroring OSVR and thus distorted and not separate as depicted in control panel.

**Comment by rpavlik** [comment]
There is nothing that anyone except NVIDIA and Intel (or maybe Microsoft) can do to get direct mode working on such a hybrid graphics solution under Windows, sorry. Inherent limitations in the topology they've chosen for the device. At least with AMD discrete graphics along with Intel integrated, there seems there might be a possibility of a higher-performance VR suitable mode coming along the pipe in Linux, but even that's speculative at this point, just figured it was worth noting.

Closing because there's nothing I can do here. (and because OSVR works well on Windows 10 for quite some time now.)
