### ISSUE TITLE
Persistence / Motion Blur

### ISSUE THREAD

**Issue by Chrjstoph** [OSVR/OSVR-General#9]
I would like some second opinion on the rendering experience.

I have tried the various examples and stepped through the persistence modes and notice that there is (still) some heavy motion blur.

It "feels" that the low persistence rendering is even worse, since the contrast are weaker and the eye seems to do its perception magic even better.

So, is there a solution to the blur or are 60Hz just insufficient?

**Comment by rpavlik** [comment]
Sorry for the delay in reply. While you might no longer be interested, I figured I'd answer anyway just for completeness.

There's nothing about 60Hz that makes motion blur or persistence inherent - persistence is independent of refresh rate. What you're probably seeing is the result of some mis-communications with the panel vendor - some HDK 1.x models shipped with a "double-pulsing" panel that still updated the image at only 60Hz but "flashed" the screen at 120 Hz (displaying each frame twice). While this might be useful in a non-head-coupled display, this is actually counter-productive for HMDs since by the time the panel flashes a second time, that image is now in the "wrong place" if you've turned your head at all, but the flash makes the "wrong" image more visible again. This causes a blurring/stuttering effect that is not a good thing.

After working with the vendor, we initially were able to get the panel to pulse at 240 Hz (so 4 weaker flashes of a single image) - which was still not ideal but subjectively better than the 120 Hz flashing. After additional work, we were able to get the display commands to switch the panel back into a low-persistence (short illumination time) 60Hz mode, which looks the best.

You can switch between these using the "OSVR Control" utility (or for the true geeks, using the serial console of the HMD). The settings do get saved, but bugs in the firmware if you're using something other than the latest might cause this to not work correctly, so I'd recommend updating to the latest firmware and then going in and changing the persistence level and flash rate (IIRC they might be set independently?) in OSVR Control, to re-write the eeprom settings that store these default values.

Hope this is useful to someone!
